version: '3.8'
services:
  app:
    build: .
    image: php:7.4.33-apache
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DBLibros
      MYSQL_USER: user
      MYSQL_PASSWORD: password
